# Generated by Django 4.1.2 on 2024-05-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_booking_created_at_booking_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
