# Generated by Django 4.1.2 on 2024-05-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name="Booking",
        # ),
    ]
