# Generated by Django 5.0.3 on 2024-04-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='doneness',
            field=models.CharField(blank=True, choices=[('WELL_DONE', 'WELL DONE'), ('MEDIUM', 'MEDIUM'), ('RARE', 'RARE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_type',
            field=models.CharField(choices=[('BEEF', 'Beef'), ('SAUCES', 'Sauces'), ('DESSERT', 'Dessert'), ('DRINK', 'Drink'), ('SOUP', 'Soup'), ('TRADITIONAL', 'Traditional'), ('POPULAR', 'Popular')], default='POPULAR', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='weight',
            field=models.IntegerField(blank=True, choices=[(250, '250g'), (350, '350g'), (200, '200G'), (300, '300g'), (500, '500g')], null=True),
        ),
    ]
