# Generated by Django 4.1.2 on 2024-05-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0009_alter_menuitem_price_currency_and_more"),
        ("deliveries", "0009_menuitem_item_type"),
    ]

    operations = []
