# Generated by Django 4.1.2 on 2024-05-30 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checkout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Họ")),
                ("last_name", models.CharField(max_length=100, verbose_name="Tên")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Số điện thoại"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Địa chỉ"),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày giao hàng"
                    ),
                ),
                (
                    "delivery_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Thời gian giao hàng"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Phí ship",
                    ),
                ),
                (
                    "vat",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Thuế"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Tổng cộng",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("paypal", "PayPal/Credit Card"),
                            ("cod", "Cash on Delivery"),
                        ],
                        max_length=11,
                        verbose_name="Phương thức thanh toán",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
