# Generated by Django 4.1.2 on 2024-05-30 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_checkout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="valid_from",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 30, 15, 10, 8, 607672)
            ),
        ),
    ]
