# Generated by Django 4.1.2 on 2024-05-30 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_alter_voucher_valid_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="valid_from",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 30, 8, 19, 32, 420871, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
