# Generated by Django 4.1.2 on 2024-05-30 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_alter_voucher_valid_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="valid_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
