# Generated by Django 5.0.6 on 2024-05-31 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_orderco_delivery_date_orderco_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 18, 36, 29, 428642)),
        ),
    ]
