# Generated by Django 4.1.2 on 2024-05-30 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0006_alter_voucher_valid_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="valid_from",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 30, 15, 37, 49, 499442)
            ),
        ),
    ]
