# Generated by Django 5.0.6 on 2024-05-30 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_voucher_discount_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='valid_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 19, 4, 58, 280772)),
        ),
    ]
